### ISSUE TITLE
FluidList.nPropane doesn't work due to N-PROPANE misspelling

### ISSUE THREAD

**Issue by strommen** [MadsKirkFoged/SharpFluids#14]
Trying to create a `Fluid` with `FluidList.nPropane` doesn't work.  It looks like "N-PROPANE" on the `MediaType` attribute is missing the E.

Creating a Fluid with `new MediaType(("HEOS", "N-PROPANE", MixType.Mass, 1.0)` works correctly.

**Comment by MadsFoged** [comment]
It should be fixed now!
You're absolutely correct the 'e' was missing - Thank you strommen for reporting the problem!
