### ISSUE TITLE
Fluid Enthalpy should return an Enthalpy type not SpecificEnergy

### ISSUE THREAD

**Issue by romarro** [MadsKirkFoged/SharpFluids#19]
If I Have the following:
wg = new Fluid(...)

Enthalpy H = wg.Enthalpy

gives an error:
cannot convert from 'EngineeringUnits.SpecificEnergy' to 'EngineeringUnits.Enthalpy'	

Why the Fluid doesn't return Enthalpy and a SpecificEnergy? 
I can explicitly convert the SpecificEnergy to Enthalpy, I know that, but it ads complexity to the code.

**Comment by MadsKirkFoged** [comment]
Should be fixed, it was a bug from my side! Thanks for reporting it!

**Comment by romarro** [comment]
Ths is working. Thanks
