### ISSUE TITLE
using SharpFluids: could not be found in .NET Core 

### ISSUE THREAD

**Issue by jeisonjei** [MadsKirkFoged/SharpFluids#2]
Hello, 
on my computer in the console application `using SharpFluids;` directive doesn't see the library, 
in the same time `using UnitsNet;` points to the library without problem
`.NET Core framework version 3.1.302`

Thank you

**Comment by MadsFoged** [comment]
I have not yet tested it in .Net Core

I will see what I can do to make it work in .Net Core

**Comment by jeisonjei** [comment]
Thank you!

**Comment by MadsFoged** [comment]
Should be fixed now!

**Comment by jeisonjei** [comment]
Thank you very much! I'm planning to use it for this [https://heatcalc.space/](url) since I was not be able to make Coolprop working
