### ISSUE TITLE
WetBulbTemperature MoistAir bug

### ISSUE THREAD

**Issue by kurupt44** [MadsKirkFoged/SharpFluids#27]
Hello,

Moist Air returned value for the Wet Bulb Tempetature is wrong, this is the Dew Point Temperature that is returned,

How correct it?

Thank you

**Comment by MadsKirkFoged** [comment]
Hi kurupt44,

Thanks for reporting the bug! It should be fixed now.
Can you verify that it is fixed by upgrading and trying it out?

**Comment by kurupt44** [comment]
Hi,
Perfect it is ok now,
Thank you
