### ISSUE TITLE
Fluid.Pressure is counting for 1/10 the expected value

### ISSUE THREAD

**Issue by Sean-Hasse** [MadsKirkFoged/SharpFluids#31]
I've been testing some code meant to take user-generated Temperatures and Pressures and a selected fluid and automatically generate a Density and Dynamic Viscosity, and this NuGet package is basically perfect. 
However, when testing my code against expected values, I found that I was running pretty far behind them. 

For example, Water at 20*C and 2300 Pa should give about 998 kg/m3 Density and .0010014 Pa*s Dyn Visc, but to get those correct outputs, I need the user to put Water at 20*C and 23000 Pa, 10x the Pressure. 

For the code, all I'm calling is fluid.UpdatePT(inputPressure, inputTemp), then calling fluid.Density and fluid.DynVisc later. I can confirm that the pressure and Temperature are the correct values when calling this method, and that the properties are properly updated, that is that fluid.Temperature and fluid.Pressure return the same values as the input. 

As far as I can tell, it appears that the Pressure is counting for 1/10 the value it should when being used to calculate Density and Dynamic Viscosity at a minimum. I've also tested using different units, double checking the units of the output and the input, and so on. When I call fluid.UpdatePT(inputPressure * 10, inputTemp), I get the expected Density and DynVisc values, but of course the Density is then set to be 10x what the user selected. Any insight into what could be causing this or how to resolve it without changing the Pressure like that would be really appreciated.

**Comment by MadsKirkFoged** [comment]
Im glad that you found this place then :)

When looking water up for this condition, 
``` C#
Fluid Water = new Fluid(FluidList.Water);
Water.UpdatePT(Pressure.FromPascals(2300), Temperature.FromDegreesCelsius(20));
```
I get that the `Phase = Gas`. 
Which means that you dont have liquid water but water vapor and that changes the properties a lot.

Try comparing these values instead (where the  `Phase = liquid `)
``` C#
Fluid Water = new Fluid(FluidList.Water);
Water.UpdatePT(Pressure.FromPascals(2340), Temperature.FromDegreesCelsius(20));
```

Does that bring you closer to what you expected?

**Comment by Sean-Hasse** [comment]
Yes, in fact I found that I really had been mis-reading the table I was using to compare values the whole time. >.>

I was using saturation pressure (where the water will just barely turn into a gas) at temperatures below 100 *C, but the table only specifies it uses that pressure at temperatures above 100 *C, which makes sense. That's why I was getting a gas, and why my properties were off so much. Thank you for the quick response!
