### ISSUE TITLE
Linux .NET6.0 SharpFluids Thew System.DllNotFoundException

### ISSUE THREAD

**Issue by theodoreOnzGit** [MadsKirkFoged/SharpFluids#37]
Hi MadsKirkFoged,

Thanks for making this library, 

I've run code similar to this in a unit test on a windows PC, it works beautifully.

```csharp
using SharpFluids;
using EngineeringUnits;
using EngineeringUnits.Units;
using System;

// make a new therminol-VP1 fluid object

Fluid therminol = new Fluid(FluidList.InCompTherminolVP1);

// set temperature and pressure

Pressure atmosphericPressure = new Pressure(1.1013e5, PressureUnit.Pascal);
EngineeringUnits.Temperature roomTemperature 
= new EngineeringUnits.Temperature(293, TemperatureUnit.Kelvin);

// update PT of therminol
// updates the temperature and pressure of therminol

therminol.UpdatePT(atmosphericPressure, roomTemperature);

// obtain prandtl number
Console.WriteLine(therminol.Prandtl);
 ```

Unfortunately, i ran the same code on my linux machine and it threw me a DllnotFoundException.

I looked in my binary files and the dll was there...

```zsh

watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + R" to restart.
watch : Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  linuxCoolPropTest -> /home/teddy0/Documents/youTube/spiceSharpFluidFlowSolver/linuxCoolPropTest/bin/Debug/net6.0/linuxCoolPropTest.dll
watch : Started
Unhandled exception. System.TypeInitializationException: The type initializer for 'CoolPropPINVOKE64' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'CoolProp64' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libCoolProp64: cannot open shared object file: No such file or directory
   at CoolPropPINVOKE64.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_CoolProp(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at CoolPropPINVOKE64.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at CoolPropPINVOKE64.SWIGExceptionHelper..ctor()
   at CoolPropPINVOKE64..cctor()
   --- End of inner exception stack trace ---
   at CoolPropPINVOKE64.AbstractState_factory__SWIG_0(String jarg1, String jarg2)
   at AbstractState.factory(String backend, String fluid_names)
   at SharpFluids.Fluid.SetNewMedia(MediaType Type)
   at SharpFluids.Fluid..ctor(MediaType Media)
   at SharpFluids.Fluid..ctor(FluidList Type)
   at Program.<Main>$(String[] args) in /home/teddy0/Documents/youTube/spiceSharpFluidFlowSolver/linuxCoolPropTest/Program.cs:line 9
watch : Exited with error code 134
watch : Waiting for a file to change before restarting dotnet...
```

I can of course take a look at it, but have limited time to do so and try and debug this.

I do hope you can take a look also.

But once again, thank you for this package.

**Comment by theodoreOnzGit** [comment]
Update: After doing some research i found this article on microsoft docs, which may lead us to a possible fix

https://docs.microsoft.com/en-us/dotnet/standard/native-interop/cross-platform

The documentation says that when Dllimport is called on windows

It will look for

CoolProp64
CoolProp64.dll

But when its run on linux, it will look for

CoolProp64.so
libCoolProp64.so

Such a call is invoked here:

```csharp

        [DllImport("CoolProp64", EntryPoint = "SWIGRegisterExceptionCallbacks_CoolProp")]
        public static extern void SWIGRegisterExceptionCallbacks_CoolProp(
                                    ExceptionDelegate applicationDelegate,
                                    ExceptionDelegate arithmeticDelegate,
                                    ExceptionDelegate divideByZeroDelegate,
                                    ExceptionDelegate indexOutOfRangeDelegate,
                                    ExceptionDelegate invalidCastDelegate,
                                    ExceptionDelegate invalidOperationDelegate,
                                    ExceptionDelegate ioDelegate,
                                    ExceptionDelegate nullReferenceDelegate,
                                    ExceptionDelegate outOfMemoryDelegate,
                                    ExceptionDelegate overflowDelegate,
                                    ExceptionDelegate systemExceptionDelegate);
```
However on linux, no CoolProp64.so is found, so the exception is thrown

While .Net Core does compile dlls, the original coolprop libraries are written in C/C++ which needs to compile to .so files
on linux in order to work.

The solution then is to compile an equivalent CoolProp64.so using the same source files and update the Nuget package.

Otherwise, this SharpFluids library may remain non cross platform.

Would just like to know what are the source files you used to compile the dll?
Are they from here?

https://github.com/CoolProp/CoolProp

If so, i guess the fix is simple: compile a corresponding CoolProp64.so and the issue should be fixed

A similar approach was used in SharpProp which uses UnitsNet (but i prefer your EngineeringUnits package)

https://github.com/portyanikhin/SharpProp/tree/master/SharpProp

you can see the repo here contains both libCoolProp.dll and libCoolProp.so

i might even just download the libCoolProp.so files from there, rename it to CoolProp64.so and test it. 
Otherwise i'll compile coolprop from source and just dump the CoolProp64.so file in the bin folder and try this out. 

However, it's been a long week and i need to rest, i'll test it later, but if you are able to do the same thing, let me know also!

Thank you!

**Comment by theodoreOnzGit** [comment]
Update: the fix

I copied the libCoolProp.so library from:
https://github.com/portyanikhin/SharpProp

and i renamed it as libCoolProp64.so

when i ls /bin/Debug:

```zsh
CoolProp64.dll  EngineeringUnits.dll  libCoolProp64.so   linuxCoolPropTest.deps.json  linuxCoolPropTest.pdb                 Microsoft.Bcl.HashCode.dll  ref          SharpFluids.dll
CoolProp.dll    Fractions.dll         linuxCoolPropTest  linuxCoolPropTest.dll        linuxCoolPropTest.runtimeconfig.json  Newtonsoft.Json.dll         Serilog.dll
```

And then i run dotnet watch on the code:

```csharp

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.108

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + R" to restart.
watch : Building...
  Determining projects to restore...
  Restored /home/teddy0/Documents/youTube/spiceSharpFluidFlowSolver/linuxCoolPropTest/linuxCoolPropTest.csproj (in 2.3 sec).
  linuxCoolPropTest -> /home/teddy0/Documents/youTube/spiceSharpFluidFlowSolver/linuxCoolPropTest/bin/Debug/net6.0/linuxCoolPropTest.dll
watch : Started
47.07742024096021
watch : Exited
watch : Waiting for a file to change before restarting dotnet...
```

I was kind of in a rush so i didn't even bother compiling the binary. I just copied it from another git repo.
I don't know what steps they took to compile it. If I ever found it out i'll let you know...

I don't know if SharpProp has their own in house cmake file. But their .so library definitely works.

If you could just copy it and then add it to the repo that will help tons. Thanks!

**Comment by theodoreOnzGit** [comment]
Update:

For consistency's sake i cloned the coolprop git into my own
computer to try compiling my own libCoolProp64.so:

Apparently coolProp uses mono to compile the C# wrappers. I thought that would conflict with .Net6.0 and all, but thank God it didn't.

In Arch linux i used pacman to install:

mono
cython
python
swig
python2-six
python2 
p7zip

(hope i didn't miss any dependencies, i already installed a lot of other libraries and development software on my system)

python2 is important since that's what the cmake compiler
uses to compile the code.

I then followed the instructions here: 

http://www.coolprop.org/coolprop/wrappers/Csharp/index.html#user-compiled-binaries

```zsh
# Check out the sources for CoolProp
git clone https://github.com/CoolProp/CoolProp --recursive
# Move into the folder you just created
cd CoolProp
# Make a build folder
mkdir build && cd build
# Build the makefile using CMake
cmake .. -DCOOLPROP_CSHARP_MODULE=ON -DBUILD_TESTING=ON
# Make the C# files (by default files will be generated in folder install_root/Csharp relative to CMakeLists.txt file)
cmake --build .
```

thereafter i moved the .so file into my own projects folder
and i added this line in the .csproj file under the itemgroup
xml file

```xml
  <ItemGroup>
	  <None Include="libCoolProp64.so" PackagePath="build\" Pack="true" />
  <None Update="libCoolProp64.so">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <PackagePath>build\</PackagePath>
	  <Pack>true</Pack>
  </None>
  </ItemGroup>
```

Which is basically whatever i found in your .csproj file and i replaced CoolProp64.dll with libCoolProp64.so

So that when dotnet build is called, it will be pushed into the Debug folder where the exe files are.

And basically the library works.

I intend to create a pull request later on, at least once i figure out the forking and everything later...

**Comment by MadsKirkFoged** [comment]
You are welcome to make this compatible with linux! I dont use linux myself so I cant help you alot..

Alternative, you can try to use [SharpProp](https://github.com/portyanikhin/SharpProp). I haven't tested it, but it looks like it has all the same features and more.

**Comment by theodoreOnzGit** [comment]
Thanks MadsKirkFoged!

While I see SharpProp, i don't really like that its .Net5.0 only.

I like it that it's .NetStandard2.0 here, which allows it to be cross compatible with both .Net Framework and .NET Core.

 And not only that, your engineering units package is much more feature rich than UnitsNet. 

The only thing to truly make it cross compatible everywhere as the .Netstandard2.0 suggests is perhaps cross platform compatibility.

I'll make a pull request shortly

**Comment by theodoreOnzGit** [comment]
I tested the new nuget package
SharpFluids version 3.0.280 on 

```zsh
                   -`                    teddy0@archSSDandVMDesktop 
                  .o+`                   -------------------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: NH5x_7xDCx_DDx 
               `+oooooo:                 Kernel: 5.15.59-2-lts 
               -+oooooo+:                Uptime: 5 days, 8 hours, 40 mins 
             `/:-:++oooo+:               Packages: 1782 (pacman), 7 (flatpak) 
            `/++++/+++++++:              Shell: bash 5.1.16 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: Plasma 5.25.4 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         Theme: [Plasma], Breeze [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: [Plasma], candy-icons [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: vscode 
     /ossssssss/        +ssssooo/-       CPU: Intel i7-10875H (16) @ 5.100GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: Intel CometLake-H GT2 [UHD Graphics] 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce RTX 2060 Mobile 
 `++:.                           `-/+/   Memory: 6860MiB / 31801MiB 
 .`                                 `/
                                                                 
                                                                 

```

The code was run in .NET6.0

```csharp
using SharpFluids;
using EngineeringUnits;
using EngineeringUnits.Units;
using System;

Console.WriteLine("Hello, World!");

Fluid therminol = 
new Fluid(FluidList.InCompTherminolVP1);

Pressure atmosphericPressure = 
new Pressure(1.013e5, PressureUnit.Pascal);

EngineeringUnits.Temperature roomTemperature = 
new EngineeringUnits.Temperature(293, 
		TemperatureUnit.Kelvin);

therminol.UpdatePT(atmosphericPressure,
		roomTemperature);

Console.WriteLine(therminol.Prandtl);
```

And this resulted in:

```zsh
watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + R" to restart.
watch : Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  therminolTest -> /home/teddy0/Documents/youTube/dotnet/therminolTest/bin/Debug/net6.0/therminolTest.dll
watch : Started
Hello, World!
47.07742024096021
watch : Exited
watch : Waiting for a file to change before restarting dotnet...

```

Therefore, SharpFLuids 3.0.280 has been tested for linux x86_64 (64 bit) support. At least on Arch.

Ubuntu and others yet to be tested.

32 bit support not yet implemented. But I suppose can do that later.
