### ISSUE TITLE
CO2 cannot get the Surface Tension value

### ISSUE THREAD

**Issue by sdwdjzhy** [MadsKirkFoged/SharpFluids#51]
#r "nuget: SharpFluids, 3.0.404"

```C#
using System.Data;
using EngineeringUnits;
using SharpFluids;

var fluid = new Fluid(FluidList.CO2);
fluid.UpdateXT(1, temperature: Temperature.FromDegreesCelsius(-40.8));

fluid.SurfaceTension.Dump();
```
the result is 0

but Refprop Excel  result    =SurfaceTension("co2.fld","tliq","SI with C",-40.8)  is  12.86026325 dyne /cm

how can i do next?
thanks

**Comment by MadsKirkFoged** [comment]
I believe that SurfaceTension is only valid in 2phase.
Try moving it into the 2phase

```
using System.Data;
using EngineeringUnits;
using SharpFluids;

var fluid = new Fluid(FluidList.CO2);
fluid.UpdateXT(0.5, temperature: Temperature.FromDegreesCelsius(-40.8));

fluid.SurfaceTension.Dump();
```
[Not tested]

**Comment by sdwdjzhy** [comment]
You are right, I use `fluid.UpdateXT(0.99999, temperature: Temperature.FromDegreesCelsius(-40.8));`  the result similar to Refprop.

Thank you
