### ISSUE TITLE
Store FluidList on instantiation?

### ISSUE THREAD

**Issue by wiwalsh** [MadsKirkFoged/SharpFluids#6]
It would be nice to have a property that contains the FluidList in the object Fluid when Fluid is created.  It looks like all that happens is the FluidList in the ctor is used to set up the AbstractState.factory.  Any reason this can't be stored in a property?

**Comment by MadsFoged** [comment]
I guess it could be - What do we gain from putting it in a property?

**Comment by MadsFoged** [comment]
When you create a new fluid like this:
`Refrigerant Input = new Refrigerant(SharpFluids.FluidList.Ammonia);`

It stores the fluidtype in
`Input.Media`

Its name is found in
`Input.Media.InternalName`

Was that what you were looking for?

**Comment by wiwalsh** [comment]
For now I think this works.  I'll re-open if I run into issues.
